{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Import package\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from geopy.geocoders import Nominatim\n",
    "import matplotlib\n",
    "from geopy.distance import geodesic\n",
    "from shapely.geometry import Point, MultiPoint\n",
    "from shapely.ops import nearest_points\n",
    "from datetime import datetime, timedelta, date\n",
    "import network_analysis_module"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# - Import data -\n",
    "aed = pd.read_parquet('aed_locations.parquet.gzip')\n",
    "postal_codes_subset = pd.read_csv('postal_codes.csv', sep=',')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     id  type                address  number  postal_code municipality  \\\n",
      "0  13.0  None    Blvd. Fr. Roosevelt    24.0       7060.0     SOIGNIES   \n",
      "1  70.0  None        Ch. De Wégimont    76.0       4630.0      Ayeneux   \n",
      "2  71.0  None  Place Saint - Lambert     NaN       4020.0        Liège   \n",
      "3  72.0  None          Rue du Doyard     NaN       4990.0     Lierneux   \n",
      "4  73.0  None     Fond Saint Servais     NaN       4000.0        Liège   \n",
      "\n",
      "  province location public available hours  \n",
      "0  Hainaut     None      Y      None  None  \n",
      "1    Liège     None   None      None  None  \n",
      "2    Liège     None   None      None  None  \n",
      "3    Liège     None   None      None  None  \n",
      "4    Liège     None   None      None  None  \n"
     ]
    }
   ],
   "source": [
    "# AED\n",
    "print(aed.head())\n",
    "aed_cl=aed.copy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "for column in aed_cl.columns:\n",
    "    if aed_cl[column].dtype=='object':\n",
    "        aed_cl[column]=aed_cl[column].str.title().str.strip()\n",
    "    else:\n",
    "        aed_cl[column]=aed_cl[column]    \n",
    "\n",
    "aed_cl.loc[aed_cl['type'].isin(['Appareil fixe','Appareil Fixe','Appareil fixe-Vast apparaat','Vast apparaat','Vast apparaat']),'type']='Fixed'\n",
    "aed_cl.loc[aed_cl['type'].isin(['Appareil Mobile- Mobiel apparaat','M5066A']),'type']='Mobile'\n",
    "\n",
    "aed_cl['postal_code']=aed_cl['postal_code'].astype('str').str.replace('.0','')\n",
    "\n",
    "for index, value in aed.iterrows():\n",
    "    if aed_cl.iloc[index, 8] in ['J', 'Ja', 'Oui', 'Oui-Ja', 'y', 'Y']:\n",
    "        aed_cl.loc[index, 'public'] = 'Yes'\n",
    "    elif aed_cl.iloc[index, 8] in ['Non-Nee', 'N', 'Nee']:\n",
    "        aed_cl.loc[index, 'public'] = 'No'\n",
    "    else:\n",
    "        aed_cl.iloc[index, 8] = 'None'\n",
    "        \n",
    "for index, value in aed.iterrows():\n",
    "    if aed_cl.iloc[index, 9] in ['J', 'Ja', 'Oui', 'Oui-Ja', 'y', 'Y', 'oui via interphone','Accessible par toute personne présente dans l inrfastructure.','Oui-Ja \"Niet tijdens activiteiten van de wielervrienden\"']:\n",
    "        aed_cl.loc[index, 'available'] = 'Yes'\n",
    "    elif aed_cl.iloc[index, 9] in ['Non-Nee', 'N', 'Nee']:\n",
    "        aed_cl.loc[index, 'available'] = 'No'\n",
    "    elif aed_cl.iloc[index, 9] in ['09.00 - 17.00', '9.00 - 17.00', 'Nee']:\n",
    "        aed_cl.loc[index, 'available'] = '09.00 - 17.00'\n",
    "    elif aed_cl.iloc[index, 9] in ['09u-12u en op aanvraag']:\n",
    "        aed_cl.loc[index, 'available'] = '09.00 - 12.00'\n",
    "    elif aed_cl.iloc[index, 9] in ['5h00 à 25h00', 'de 5h00 à 25h00']:\n",
    "        aed_cl.loc[index, 'available'] = '05.00 - 23.59'\n",
    "    elif aed_cl.iloc[index, 9] in ['8:00 - 17:00', 'N', 'Nee']:\n",
    "        aed_cl.loc[index, 'available'] = '8:00 - 17:00'\n",
    "    elif aed_cl.iloc[index, 9] in ['16u-23u tijdens opening sporthal']:\n",
    "        aed_cl.loc[index, 'available'] = '16.00 - 23.00'\n",
    "    elif aed_cl.iloc[index, 9] in ['De 5h30 à 21h30']:\n",
    "        aed_cl.loc[index, 'available'] = '05.30 - 21.30'\n",
    "    elif aed_cl.iloc[index, 9] in ['Dispo 24/7 - sauf samedi de 12h à dimanche 20h', 'Dispo. tout le temps sauf du samedi midi au dimanche 21h']:\n",
    "        aed_cl.loc[index, 'available'] = '00.00 - 23.59'\n",
    "    elif aed_cl.iloc[index, 9] in ['Heure de bureau en semaine', 'Heures de bureau', 'Horaire d ouverture de la buvette','Pendant heures d ouverture du site',\n",
    "                                   'Pendant les heures de cours','Tijdens de kantooruren','Tijdens kantooruren','Tijdens openingsuren van het museum','enkel tijdens kantooruren',\n",
    "                                   'enkel tijdens de kantooruren (8 - 19u)','horaire d ouverture de la pharmacie','indien de site open is, volledig toegangkelijk','kantooruren',\n",
    "                                   'selon heures d ouverture d Euro-Délices','tijdens de kantooruren','tijdens de kantooruren in de week','tijdens de openingsuren','tijdens de werkuren',\n",
    "                                   'tijdens onze openingsuren, zie nr. 12','tijdens openinguren sportcentrum','tijdens werkuren','zie rooster','Heures de bureau ']:\n",
    "        aed_cl.loc[index, 'available'] = 'Working Opening Time'\n",
    "    elif aed_cl.iloc[index, 9] in ['maandag, dinsdag, donderdag, vrijdag', 'du lundi au vendredi ']: \n",
    "        aed_cl.loc[index, 'available'] = 'During Weekdays'\n",
    "    else:\n",
    "        aed_cl.iloc[index, 9] = 'None'  \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'7060'"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "aed_cl.dtypes\n",
    "aed_cl['postal_code'].iloc[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0     7060\n",
      "1     4630\n",
      "2     4020\n",
      "3     4990\n",
      "4     4000\n",
      "      ... \n",
      "95    1160\n",
      "96    1200\n",
      "97    1070\n",
      "98    3290\n",
      "99    3980\n",
      "Name: postal_code, Length: 100, dtype: object\n"
     ]
    }
   ],
   "source": [
    "print(aed_cl['postal_code'].head(100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "aed_cl['postal_code'] = aed_cl.apply(lambda x: float(x['postal_code']), axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "id, column number 0\n",
      "type, column number 1\n",
      "address, column number 2\n",
      "number, column number 3\n",
      "postal_code, column number 4\n",
      "municipality, column number 5\n",
      "province, column number 6\n",
      "location, column number 7\n",
      "public, column number 8\n",
      "available, column number 9\n",
      "hours, column number 10\n",
      "postcode, column number 11\n",
      "smun_code, column number 12\n",
      "reg_code, column number 13\n",
      "prov_code, column number 14\n",
      "arr_code, column number 15\n",
      "mun_code, column number 16\n",
      "Region, column number 17\n",
      "Province, column number 18\n",
      "Arrondissement, column number 19\n",
      "Municipality, column number 20\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>type</th>\n",
       "      <th>address</th>\n",
       "      <th>number</th>\n",
       "      <th>Region</th>\n",
       "      <th>Province</th>\n",
       "      <th>Arrondissement</th>\n",
       "      <th>Municipality</th>\n",
       "      <th>type</th>\n",
       "      <th>postal_code</th>\n",
       "      <th>public</th>\n",
       "      <th>available</th>\n",
       "      <th>hours</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>13.0</td>\n",
       "      <td>None</td>\n",
       "      <td>Blvd. Fr. Roosevelt</td>\n",
       "      <td>24.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Hainaut (le)</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>None</td>\n",
       "      <td>7060.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>70.0</td>\n",
       "      <td>None</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>None</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>70.0</td>\n",
       "      <td>None</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>None</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>71.0</td>\n",
       "      <td>None</td>\n",
       "      <td>Place Saint - Lambert</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>None</td>\n",
       "      <td>4020.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>72.0</td>\n",
       "      <td>None</td>\n",
       "      <td>Rue Du Doyard</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Verviers</td>\n",
       "      <td>Lierneux</td>\n",
       "      <td>None</td>\n",
       "      <td>4990.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     id  type                address  number    Region      Province  \\\n",
       "0  13.0  None    Blvd. Fr. Roosevelt    24.0  Wallonia  Hainaut (le)   \n",
       "1  70.0  None        Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "2  70.0  None        Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "3  71.0  None  Place Saint - Lambert     NaN  Wallonia         Liège   \n",
       "4  72.0  None          Rue Du Doyard     NaN  Wallonia         Liège   \n",
       "\n",
       "  Arrondissement Municipality  type  postal_code public available hours  \n",
       "0       Soignies     Soignies  None       7060.0    Yes      None  None  \n",
       "1          Liège     Soumagne  None       4630.0   None      None  None  \n",
       "2          Liège     Soumagne  None       4630.0   None      None  None  \n",
       "3          Liège        Liège  None       4020.0   None      None  None  \n",
       "4       Verviers     Lierneux  None       4990.0   None      None  None  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "aed_all = pd.merge(aed_cl,postal_codes_subset, left_on = 'postal_code', right_on = 'postcode', how ='left')\n",
    "for a, b in zip(aed_all.columns, range(0,len(aed_all.columns))):\n",
    "                print(f'{a}, column number {b}')\n",
    "\n",
    "aed_subset = aed_all.iloc[:,[0,1,2,3,17,18,19,20,1,4,8,9,10]]\n",
    "aed_subset.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "# postal_codes_subset.to_csv('postal_codes.csv', index=False)\n",
    "aed_subset.to_csv('aed.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>type</th>\n",
       "      <th>address</th>\n",
       "      <th>number</th>\n",
       "      <th>Region</th>\n",
       "      <th>Province</th>\n",
       "      <th>Arrondissement</th>\n",
       "      <th>Municipality</th>\n",
       "      <th>type.1</th>\n",
       "      <th>postal_code</th>\n",
       "      <th>public</th>\n",
       "      <th>available</th>\n",
       "      <th>hours</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>13.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Blvd. Fr. Roosevelt</td>\n",
       "      <td>24.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Hainaut (le)</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>NaN</td>\n",
       "      <td>7060.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>70.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>70.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>71.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Place Saint - Lambert</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4020.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>72.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Rue Du Doyard</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Verviers</td>\n",
       "      <td>Lierneux</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4990.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     id type                address  number    Region      Province  \\\n",
       "0  13.0  NaN    Blvd. Fr. Roosevelt    24.0  Wallonia  Hainaut (le)   \n",
       "1  70.0  NaN        Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "2  70.0  NaN        Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "3  71.0  NaN  Place Saint - Lambert     NaN  Wallonia         Liège   \n",
       "4  72.0  NaN          Rue Du Doyard     NaN  Wallonia         Liège   \n",
       "\n",
       "  Arrondissement Municipality type.1  postal_code public available hours  \n",
       "0       Soignies     Soignies    NaN       7060.0    Yes       NaN   NaN  \n",
       "1          Liège     Soumagne    NaN       4630.0    NaN       NaN   NaN  \n",
       "2          Liège     Soumagne    NaN       4630.0    NaN       NaN   NaN  \n",
       "3          Liège        Liège    NaN       4020.0    NaN       NaN   NaN  \n",
       "4       Verviers     Lierneux    NaN       4990.0    NaN       NaN   NaN  "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "aed_df = pd.read_csv('aed.csv', sep=',')\n",
    "aed_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CLEANING AND ADJUSTING AED DATAFRAME\n",
    "\n",
    "## - NOT USE ANYMORE, SOLVING OF PREVIOUS ISSUES REMOVE THIS REQUIREMENT\n",
    "# # 1. Clean wierd characters\n",
    "\n",
    "# aedClean_df = aed_df\n",
    "# column_names = list(aedClean_df.columns.values)\n",
    "# # print(column_names)\n",
    "# for name in column_names:\n",
    "#     if isinstance(aedClean_df[name][1], str): #not robust if value of row 1 is missing!\n",
    "#         print(name)\n",
    "#         aedClean_df[name] = aedClean_df[name].str.replace('Ã¨','è')\n",
    "#         aedClean_df[name] = aedClean_df[name].str.replace('Ã©','é')\n",
    "#         aedClean_df[name] = aedClean_df[name].str.replace('Ã§','ç')\n",
    "#         aedClean_df[name] = aedClean_df[name].str.replace('Ã´','ô')\n",
    "#         aedClean_df[name] = aedClean_df[name].str.replace('Av.','Avenue')\n",
    "#         aedClean_df[name] = aedClean_df[name].str.replace('Bd.','Boulevard')\n",
    "#         aedClean_df[name] = aedClean_df[name].str.replace('Blvd.','Boulevard')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "id                float64\n",
       "type               object\n",
       "address            object\n",
       "number            float64\n",
       "Region             object\n",
       "Province           object\n",
       "Arrondissement     object\n",
       "Municipality       object\n",
       "type.1             object\n",
       "postal_code       float64\n",
       "public             object\n",
       "available          object\n",
       "hours              object\n",
       "dtype: object"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "aed_df.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>type</th>\n",
       "      <th>address</th>\n",
       "      <th>number</th>\n",
       "      <th>Region</th>\n",
       "      <th>Province</th>\n",
       "      <th>Arrondissement</th>\n",
       "      <th>Municipality</th>\n",
       "      <th>type.1</th>\n",
       "      <th>postal_code</th>\n",
       "      <th>public</th>\n",
       "      <th>available</th>\n",
       "      <th>hours</th>\n",
       "      <th>numberStr</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>13.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Blvd. Fr. Roosevelt</td>\n",
       "      <td>24.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Hainaut (le)</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>NaN</td>\n",
       "      <td>7060.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>70.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>70.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>71.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Place Saint - Lambert</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4020.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>72.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Rue Du Doyard</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Verviers</td>\n",
       "      <td>Lierneux</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4990.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     id type                address  number    Region      Province  \\\n",
       "0  13.0  NaN    Blvd. Fr. Roosevelt    24.0  Wallonia  Hainaut (le)   \n",
       "1  70.0  NaN        Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "2  70.0  NaN        Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "3  71.0  NaN  Place Saint - Lambert     NaN  Wallonia         Liège   \n",
       "4  72.0  NaN          Rue Du Doyard     NaN  Wallonia         Liège   \n",
       "\n",
       "  Arrondissement Municipality type.1  postal_code public available hours  \\\n",
       "0       Soignies     Soignies    NaN       7060.0    Yes       NaN   NaN   \n",
       "1          Liège     Soumagne    NaN       4630.0    NaN       NaN   NaN   \n",
       "2          Liège     Soumagne    NaN       4630.0    NaN       NaN   NaN   \n",
       "3          Liège        Liège    NaN       4020.0    NaN       NaN   NaN   \n",
       "4       Verviers     Lierneux    NaN       4990.0    NaN       NaN   NaN   \n",
       "\n",
       "  numberStr  \n",
       "0        24  \n",
       "1        76  \n",
       "2        76  \n",
       "3            \n",
       "4            "
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#  2. Add numberStr column which return string format of the integer of the street number\n",
    "import math\n",
    "\n",
    "def streetnumber(number):\n",
    "    \"\"\" \n",
    "    Return string format of the input\n",
    "\n",
    "    Input:\n",
    "        number = street number [float]\n",
    "    Output:\n",
    "        string of the street number [string]\n",
    "    \"\"\"\n",
    "    if not math.isnan(number):\n",
    "        newnumber = str(int(number))\n",
    "    else:\n",
    "        newnumber = ''\n",
    "    return newnumber\n",
    "\n",
    "aed_df['numberStr'] = aed_df['number'].apply(streetnumber)\n",
    "aed_df.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# FUNCTION ALSO DEFINE IN THE MODULE 'network_analysis_module'\n",
    "\n",
    "# ADD LOCATION COORDONATE TO AED DATAFRAME\n",
    "\n",
    "# using geopy library and Nominatim class object\n",
    "# NOTE: Take long times to run (~10 min for 160 demands !)\n",
    "# Good practice to save dataframe into table !\n",
    "\n",
    "from geopy.geocoders import Nominatim\n",
    "def locationBE(numberStr, address, Arrondissement):\n",
    "    \"\"\"\n",
    "    Convert address into coordonate\n",
    "\n",
    "    Input : \n",
    "        numberStr = number of house on the street [string],\n",
    "        address = name of the street [string],\n",
    "        Arrondissement = municipality [string]\n",
    "\n",
    "    Output:\n",
    "        latitude,longitude [float,float]\n",
    "    \"\"\"\n",
    "    try:\n",
    "        geolocator = Nominatim(user_agent=\"my_user_agent\")\n",
    "        street = numberStr+' '+address\n",
    "        city = Arrondissement\n",
    "        country = 'Belgique'\n",
    "        loc = geolocator.geocode(street+','+city+','+ country, timeout=120)\n",
    "        return loc.latitude,loc.longitude\n",
    "    except:\n",
    "        return float('nan'),float('nan')\n",
    "\n",
    "# Testing locationBE function\n",
    "# lat,lon = locationBE('1','Albert Leemansplein','Bruxelles')\n",
    "# print(lat)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ISSUE: too much demand to geopy -> take too long time\n",
    "# SOLUTION : proceed by part, see next code section\n",
    "\n",
    "# # AED multipoint\n",
    "# # Take more than 1 hour\n",
    "# aed_df['Latitude','Longitude'] = aed_df.apply(lambda x: locationBE(x['numberStr'], x['address'], x['Arrondissement']), axis=1)\n",
    "# aedOK_df = aed_df[['numberStr','address','Arrondissement','Latitude','Longitude']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "177\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-1000:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1112:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1091:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1073:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1044:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1065:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-979:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-972:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1025:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1066:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-967:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1026:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1024:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1046:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1057:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1037:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-974:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-981:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-948:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "        self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "Exception in thread Thread-1096:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1075:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1007:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-955:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1038:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "Exception in thread Thread-996:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1101:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1081:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1103:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1078:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-957:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-971:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1028:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-987:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-947:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1114:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-953:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1014:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1052:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1099:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-963:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-990:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1002:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1113:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-944:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1023:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1036:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-941:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-976:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-994:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1030:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1062:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "NameError: name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1098:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-991:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1059:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-958:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-945:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "        self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-983:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1109:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1051:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "Exception in thread Thread-1027:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameErrorNameError: name 'i' is not defined\n",
      ": name 'i' is not defined\n",
      "Exception in thread Thread-1082:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-985:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-986:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1102:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1047:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-970:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1039:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1110:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1115:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1093:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1070:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-959:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1016:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1100:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1117:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1018:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-949:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1017:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-980:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "Exception in thread Thread-1050:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1041:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1029:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-946:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-969:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1013:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1072:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-964:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-956:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1049:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1012:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "Exception in thread Thread-1040:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "Exception in thread Thread-1004:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1106:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1035:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1083:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1022:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-943:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-989:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1107:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-966:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1074:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "Exception in thread Thread-1089:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "Exception in thread Thread-993:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "NameError: name 'i' is not defined\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1077:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1043:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1071:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-975:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-982:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1094:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-954:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1019:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1034:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-950:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1092:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1085:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-965:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "Exception in thread Thread-961:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      ": name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-973:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1015:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-977:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1003:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1086:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1008:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1064:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1045:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1087:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1005:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1042:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1088:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1021:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1031:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1079:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-998:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1020:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-952:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1033:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "Exception in thread Thread-1105:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameErrorNameError: name 'i' is not defined\n",
      ": name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1095:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1063:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-999:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1048:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1111:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-962:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1058:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1108:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1090:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-992:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-942:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1056:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1032:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1001:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1060:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1053:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1069:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "        self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "Exception in thread Thread-988:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "Exception in thread Thread-960:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "NameError: name 'i' is not defined\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "NameError: name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameErrorNameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      ": name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Exception in thread Thread-1116:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Thread-1006:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-951:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1054:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1084:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-978:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-997:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-968:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-1011:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "        self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    Exception in thread Thread-1068:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "_threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "Exception in thread Thread-1076:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "Exception in thread Thread-1104:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "Exception in thread Thread-984:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameErrorNameError: name 'i' is not defined\n",
      "NameErrorNameError: name 'i' is not defined\n",
      ": name 'i' is not defined\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      ": name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1067:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1055:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1097:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1080:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-995:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Thread-1010:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "Exception in thread Exception in thread Thread-1009:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Thread-1061:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"c:\\Users\\Ramy\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ramy\\AppData\\Local\\Temp\\ipykernel_4384\\2969324450.py\", line 10, in aedLocation\n",
      "NameError: name 'i' is not defined\n",
      "NameError: name 'i' is not defined\n"
     ]
    }
   ],
   "source": [
    "#AED multipoint\n",
    "import threading\n",
    "import time\n",
    "\n",
    "\n",
    "\n",
    "def aedLocation(j): #TD timeout\n",
    "    aedpart_df=aed_df.loc[(j*100):(j+1)*100]\n",
    "    aedpart_df['Latitude','Longitude'] = aedpart_df.apply(lambda x: locationBE(x['numberStr'], x['address'], x['Arrondissement']), axis=1)\n",
    "    aedpart_df.to_csv('C:\\\\aedtest\\\\aed_location_part'+str(i)+'.csv', index=False)\n",
    "    print('end : '+str(j))\n",
    "\n",
    "\n",
    "number_aed =len(aed_df) #17752\n",
    "n = int(number_aed/100)\n",
    "print(n)\n",
    "\n",
    "thread_list = []\n",
    "for j in range(n):\n",
    "    thread_list.append(threading.Thread(target=aedLocation, args=[j,]))\n",
    "    thread_list[j].start()\n",
    "\n",
    "# thread_list = []\n",
    "# for j in range(n):\n",
    "#     thread_list[j] = threading.Thread(target=aedLocation, args=(j))\n",
    "#     thread_list[j].start()\n",
    "\n",
    "# max = 16600 #then do the last 68\n",
    "# n = 166\n",
    "\n",
    "# for i in range(1, 45):\n",
    "#     aedpart_df=aed_df.loc[(i*166):(i+1)*166]\n",
    "#     aedpart_df['Latitude','Longitude'] = aedpart_df.apply(lambda x: locationBE(x['numberStr'], x['address'], x['Arrondissement']), axis=1)\n",
    "#     aedpart_df.to_csv('aedOK'+str(i)+'.csv', index=False)\n",
    "\n",
    "# # Remove data from part 42 to 46 due to issue with geopy\n",
    "# # There is an issue with data from head(42 to 44)\n",
    "\n",
    "# for i in range(45, 166):\n",
    "#     aedpart_df=aed_df.loc[(i*166):(i+1)*166]\n",
    "#     aedpart_df['Latitude','Longitude'] = aedpart_df.apply(lambda x: locationBE(x['numberStr'], x['address'], x['Arrondissement']), axis=1)\n",
    "#     aedpart_df.to_csv('aedOK'+str(i)+'.csv', index=False)\n",
    "\n",
    "#9h28"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "177\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "23\n",
      "24\n",
      "25\n",
      "22\n",
      "21\n",
      "20\n",
      "19\n",
      "18\n",
      "17\n",
      "16\n",
      "15\n",
      "14\n",
      "13\n",
      "12\n",
      "11\n",
      "10\n",
      "9\n",
      "8\n",
      "7\n",
      "6\n",
      "5\n",
      "4\n",
      "3\n",
      "2\n",
      "1\n",
      "0\n",
      "26\n",
      "76\n",
      "63\n",
      "52\n",
      "77\n",
      "74\n",
      "73\n",
      "72\n",
      "71\n",
      "70\n",
      "69\n",
      "68\n",
      "67\n",
      "66\n",
      "65\n",
      "64\n",
      "62\n",
      "61\n",
      "60\n",
      "59\n",
      "58\n",
      "57\n",
      "56\n",
      "55\n",
      "54\n",
      "53\n",
      "51\n",
      "50\n",
      "49\n",
      "48\n",
      "47\n",
      "46\n",
      "45\n",
      "78\n",
      "75\n",
      "44\n",
      "43\n",
      "42\n",
      "41\n",
      "39\n",
      "38\n",
      "40\n",
      "37\n",
      "36\n",
      "35\n",
      "34\n",
      "32\n",
      "33\n",
      "31\n",
      "30\n",
      "29\n",
      "28\n",
      "27\n",
      "79\n",
      "86\n",
      "85\n",
      "84\n",
      "83\n",
      "82\n",
      "81\n",
      "80\n",
      "104\n",
      "103\n",
      "107\n",
      "99\n",
      "91\n",
      "123\n",
      "119\n",
      "115\n",
      "111\n",
      "106\n",
      "105\n",
      "102\n",
      "101\n",
      "98\n",
      "100\n",
      "97\n",
      "96\n",
      "94\n",
      "93\n",
      "92\n",
      "90\n",
      "89\n",
      "88\n",
      "95\n",
      "124\n",
      "122\n",
      "87\n",
      "125\n",
      "121\n",
      "120\n",
      "118\n",
      "117\n",
      "116\n",
      "114\n",
      "113\n",
      "112\n",
      "110\n",
      "109\n",
      "108\n",
      "150\n",
      "153\n",
      "152\n",
      "151\n",
      "155\n",
      "147\n",
      "143\n",
      "139\n",
      "135\n",
      "171\n",
      "167\n",
      "163\n",
      "159\n",
      "156\n",
      "154\n",
      "148\n",
      "149\n",
      "146\n",
      "145\n",
      "144\n",
      "141\n",
      "140\n",
      "138\n",
      "137\n",
      "136\n",
      "134\n",
      "133\n",
      "132\n",
      "129\n",
      "128\n",
      "130\n",
      "126\n",
      "173\n",
      "172\n",
      "170\n",
      "131\n",
      "127\n",
      "169\n",
      "168\n",
      "166\n",
      "164\n",
      "162\n",
      "165\n",
      "161\n",
      "160\n",
      "158\n",
      "157\n",
      "142\n",
      "174\n",
      "175\n",
      "176\n"
     ]
    }
   ],
   "source": [
    "# import time\n",
    "# def aedLocation(j): #TD timeout\n",
    "#     time.sleep(5)\n",
    "#     print(j)\n",
    "\n",
    "\n",
    "# number_aed =len(aed_df) #17752\n",
    "# n = int(number_aed/100)\n",
    "# print(n)\n",
    "\n",
    "# thread_list = []\n",
    "# for j in range(n):\n",
    "#     thread_list.append(threading.Thread(target=aedLocation, args=[j,]))\n",
    "#     thread_list[j].start()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "aedOK1_df = pd.read_csv('aedOK1.csv', sep=',')\n",
    "aedOK1_df.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# concate the part togheter\n",
    "\n",
    "aed_list = []\n",
    "for i in range(106): #I remove the 165 because\n",
    "    if i >= 42 and i <=44:\n",
    "        continue\n",
    "    else:\n",
    "        exec(\"aedOK\"+str(i)+\"_df = pd.read_csv('aedOK\"+str(i)+\".csv', sep=',')\")\n",
    "        eval(\"aed_list.append(aedOK\"+str(i)+\"_df)\")\n",
    "\n",
    "aedCoordonate = pd.concat(aed_list)\n",
    "aedCoordonate.head(5)\n",
    "# aedCoordonate.to_csv('aedCoordonate.csv', index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>type</th>\n",
       "      <th>address</th>\n",
       "      <th>number</th>\n",
       "      <th>Region</th>\n",
       "      <th>Province</th>\n",
       "      <th>Arrondissement</th>\n",
       "      <th>Municipality</th>\n",
       "      <th>type.1</th>\n",
       "      <th>postal_code</th>\n",
       "      <th>public</th>\n",
       "      <th>available</th>\n",
       "      <th>hours</th>\n",
       "      <th>numberStr</th>\n",
       "      <th>('Latitude', 'Longitude')</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>13.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Boulevard Fr. Roosevelt</td>\n",
       "      <td>24.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Hainaut (le)</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>Soignies</td>\n",
       "      <td>NaN</td>\n",
       "      <td>7060.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>24.0</td>\n",
       "      <td>(nan, nan)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>70.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>76.0</td>\n",
       "      <td>(nan, nan)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>70.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Ch. De Wégimont</td>\n",
       "      <td>76.0</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Soumagne</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4630.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>76.0</td>\n",
       "      <td>(nan, nan)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>71.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Place Saint - Lambert</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Liège</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4020.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>(50.6451853, 5.5742929)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>72.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Rue Du Doyard</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Wallonia</td>\n",
       "      <td>Liège</td>\n",
       "      <td>Verviers</td>\n",
       "      <td>Lierneux</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4990.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>(50.2856407, 5.7808696)</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     id type                  address  number    Region      Province  \\\n",
       "0  13.0  NaN  Boulevard Fr. Roosevelt    24.0  Wallonia  Hainaut (le)   \n",
       "1  70.0  NaN          Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "2  70.0  NaN          Ch. De Wégimont    76.0  Wallonia         Liège   \n",
       "3  71.0  NaN    Place Saint - Lambert     NaN  Wallonia         Liège   \n",
       "4  72.0  NaN            Rue Du Doyard     NaN  Wallonia         Liège   \n",
       "\n",
       "  Arrondissement Municipality type.1  postal_code public available hours  \\\n",
       "0       Soignies     Soignies    NaN       7060.0    Yes       NaN   NaN   \n",
       "1          Liège     Soumagne    NaN       4630.0    NaN       NaN   NaN   \n",
       "2          Liège     Soumagne    NaN       4630.0    NaN       NaN   NaN   \n",
       "3          Liège        Liège    NaN       4020.0    NaN       NaN   NaN   \n",
       "4       Verviers     Lierneux    NaN       4990.0    NaN       NaN   NaN   \n",
       "\n",
       "   numberStr ('Latitude', 'Longitude')  \n",
       "0       24.0                (nan, nan)  \n",
       "1       76.0                (nan, nan)  \n",
       "2       76.0                (nan, nan)  \n",
       "3        NaN   (50.6451853, 5.5742929)  \n",
       "4        NaN   (50.2856407, 5.7808696)  "
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "aedCoordonate = pd.read_csv('aedCoordonate.csv', sep=',')\n",
    "aedCoordonate.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
